### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by kylonx** [frk1/steamhourboostv2#1]
I started it manually (to see if it's working), after that I got an error:

> TypeError: base64 is not a function
>   at Function.from (native)
>   at Function.from (native)
>   at SteamAccount.module.exports.SteamAccount.login (/home/root/steamhourboostv2/steamaccount.coffee:18:30)
>   at SteamAccount.login (/home/root/steamhourboostv2/steamaccount.coffee:1:1)
>   at SteamAccount.module.exports.SteamAccount.boost (/home/root/steamhourboostv2/steamaccount.coffee:35:6)
>   at SteamAccount.boost (/home/root/steamhourboostv2/steamaccount.coffee:1:1)
>   at /home/root/steamhourboostv2/boost.coffee:17:84
>   at /home/root/steamhourboostv2/node_modules/lodash/lodash.js:4411:15
>   at baseForOwn (/home/root/steamhourboostv2/node_modules/lodash/lodash.js:2654:24)
>   at /home/root/steamhourboostv2/node_modules/lodash/lodash.js:4380:18
>   at Function.forEach (/home/root/steamhourboostv2/node_modules/lodash/lodash.js:8634:14)
>   at Object.<anonymous> (/home/root/steamhourboostv2/boost.coffee:15:3)
>   at Object.<anonymous> (/home/root/steamhourboostv2/boost.coffee:1:1)
>   at Module._compile (module.js:409:26)
>   at Object.exports.run (/usr/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
>   at compileScript (/usr/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
>   at compilePath (/usr/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
>   at Object.exports.run (/usr/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
>   at Object.<anonymous> (/usr/lib/node_modules/coffee-script/bin/coffee:7:41)
>   at Module._compile (module.js:409:26)
>   at Object.Module._extensions..js (module.js:416:10)
>   at Module.load (module.js:343:32)
>   at Function.Module._load (module.js:300:12)
>   at Function.Module.runMain (module.js:441:10)
>   at startup (node.js:139:18)
>   at node.js:968:3

**Comment by frk1** [comment]
Update node to a recent version.
