### ISSUE TITLE
Where is Auto-reconnect setting?

### ISSUE THREAD

**Issue by Chino0147** [frk1/steamhourboostv2#10]
With this new version, I found 
"return _bluebird2.default.delay("5000").then(this.boost):"
in the "lib/steamaccount.js".
Is it the timer for reconnecting? And 5000 is recommended?

**Comment by frk1** [comment]
No, what you seek is in [lib/app.js](https://github.com/frk1/steamhourboostv2/blob/4.1.1/lib/app.js#L30-L40).

Time is in milliseconds.
