### ISSUE TITLE
Doesn't reconnect after auto-restart.

### ISSUE THREAD

**Issue by Chino0147** [frk1/steamhourboostv2#11]
After I left it to run for half a hour, it will do auto-restart but it doesn't reconnect to the game.
Changes I made was setting 'Online status' in 'steamaccount.js'.
How to fix this?

**Comment by Hipisuaw** [comment]
I'm exactly the same. I added one account with one game (I select CS 1.6) and I started the script. After some time, when the old script was restarted, the new version of script does not do that now. After reboot changes account status to online. I just changed - just like my friend - steamaccount.js from 'offline' to 'online'. Restoring the VPS to factory settings and reinstalling the script does nothing to help.

Sorry for my awful English.

**Comment by frk1** [comment]
Has been fixed in 1642e7d794de136e7809d47b2008bef2d1114fcf, please update the script!
