### ISSUE TITLE
Number of games per account.

### ISSUE THREAD

**Issue by ghost** [frk1/steamhourboostv2#12]
I wonder if one can actually hook up games to one account? On two different forums I heard other answers - not necessarily the script. One answer is 30, the other 33. I asked a friend using this script he wrote that he has hooked up over 30 to one account. I decided to try it and hook up about 50 and not all the hours counted. Maybe the creator will talk about this and give me an answer?

Sorry for the scruff of the tongue.

**Comment by frk1** [comment]
Generally, if it is a bought game it should work without any problems, free games are a bit tricky - Generally try playing some minutes for real and when the time shows up on your account try boosting it further.
