### ISSUE TITLE
Flood

### ISSUE THREAD

**Issue by Karlend** [frk1/steamhourboostv2#13]
Telegram bot is flooding 
ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

ijohnny.xyz, [14.11.17 18:21]
Could not find a matching account!

Try /list to get a list of available accounts!

**Comment by frk1** [comment]
What did you write the bot? What's in the log at the server? Did restarting the bot fix it? Newest version?

**Comment by Karlend** [comment]
I wrote /list . da. do. Where can i find config? Restarting bot didnt help. Last version

**Comment by frk1** [comment]
In the `config/` folder. Could you please upload the config.json (change username/password to something random) to [pastebin.com](https://pastebin.com) and post the link?
