### ISSUE TITLE
Do not start if there are no field "games"

### ISSUE THREAD

**Issue by panarama360** [frk1/steamhourboostv2#15]
if the field "games" is empty, then it does not start.
`const accounts = database
  .map(({ name, password, sentry, secret, games = [] }) => {
    return games.length > 0
      ? new SteamAccount(name, password, sentry, secret, games, pad)
      : null
  })
  .filter(val => val !== null)`
Then it turns out that this code is meaningless:
`this.client.gamesPlayed(this.games !== null ? this.games : [10, 730])`

Sorry for my bad english.

**Comment by frk1** [comment]
I know about this redundancy, I chose to leave it in case I change something in the future.
