### ISSUE TITLE
two-factor (steam guard code) doesn't work

### ISSUE THREAD

**Issue by xTrackz** [frk1/steamhourboostv2#17]
doesn't work
proof : 
http://prntscr.com/hfo5qs

**Comment by TheRhanderson** [comment]
Are you using 5 digit code or shared_key?

**Comment by xTrackz** [comment]
nvm it work I use shared key,,
but maybe can u add for hidden Recent Activity ???

**Comment by TheRhanderson** [comment]
What do you mean? Clear your recent activity from profile? There is 3 appID's that can hide that. Search on Google for the App's ID. You need to put them for last in the list.

**Comment by xTrackz** [comment]
like this 
    "games": [
      766,
      730,
      399220,
      399220,
      399080
    ]
???
