### ISSUE TITLE
Can't run with '6-digit' games

### ISSUE THREAD

**Issue by Chino0147** [frk1/steamhourboostv2#21]
It run normally with 2-3 digits games like CSGO or CS1.6 
But when I try to run it with 6 digits games it doesn't work. For example '698780' .

**Comment by juriadams** [comment]
That's really weird. Technically, it should work just fine. Can you maybe send your `database.json` file here so I could take a look? (Make sure to remove your account data and sentry etc.)

**Comment by Chino0147** [comment]
`[
  {
    "name": "account",
    "password": "password",
    "secret": "shared_secret",
    "sentry": "login_sentry
    "games": [
      698780
    ]
  }
]`

**Comment by Chino0147** [comment]
Fixed :)
You've to have that game in library.
So I have to play that free game once.
