### ISSUE TITLE
not working :/

### ISSUE THREAD

**Issue by gorkemz** [frk1/steamhourboostv2#23]
[2018-01-08 10:07:21 -xx] Starting to boost games!
but i cant see :D

**Comment by ghost** [comment]
Does the play time go up?

If you want to see "Currently In-Game xxxx" on the profile you need to change this line
https://github.com/frk1/steamhourboostv2/blob/master/lib/steamaccount.js#L81
to 
`        this.client.setPersona(SteamUser.EPersonaState.Online)`

**Comment by gorkemz** [comment]
my bad sorry :D

**Comment by gorkemz** [comment]
how can i add another games :D

**Comment by ghost** [comment]
**Existing Account:**  
edit config/database.json  
Add the games to the games array like this:  
```
    "games": [
      730,  
      NEWGAMEID,
      NEWGAMEID2,
      10190
    ]
```

**Selectable for every new account:**  
Edit lib/user.js https://github.com/frk1/steamhourboostv2/blob/master/lib/user.js#L18 and add the games to the choices array like this:  
```
  choices: [
    { value: 10, name: "CS 1.6", checked: true },
    { value: 730, name: "CS:GO", checked: true },
    { value: NEWGAMEID, name: "NEW GAME", checked: true },
    { value: NEWGAMEID2, name: "NEW GAME 2" },
    { value: 570, name: "DOTA2" }
  ]
```  
_checked: true_ sets the game to be selected by default.


You can find the Game ID in the URL of the games shop page  
[http://store.steampowered.com/app/**322500**/SUPERHOT/](http://store.steampowered.com/app/322500/SUPERHOT/)

**Comment by gorkemz** [comment]
thank youu :D
