### ISSUE TITLE
not work 2FA 

### ISSUE THREAD

**Issue by st3bgru** [frk1/steamhourboostv2#27]
Good afternoon, when I try to add an account I can not pass protection, I enter the code from the steam guard 5 characters but does not respond
![default](https://user-images.githubusercontent.com/36917492/36834122-ffb2e668-1d5b-11e8-8af8-2b979c5f6dcb.jpg)

**Comment by ghost** [comment]
Same thing with mine, except its an infinite loop of asking for authentication.

**Comment by KraKeNsaiyajiN** [comment]
Use Shared Key easy peasy XD

**Comment by Duplon** [comment]
Same issue, and not sure what you mean by shared key.

**Comment by Duplon** [comment]
Shared secret? I looked it up, but seems I can't get it on android without root. It's a different thing from steam guard.

**Comment by KraKeNsaiyajiN** [comment]
Nah use the shared key with steam desktop auth and save it after that change back to the phone again

**Comment by SiqSardines** [comment]
@KraKeNsaiyajiN how do i do it?

**Comment by frk1** [comment]
An authentication code will not work. You will need to extract the **shared secret** from your phone and use that one.

Google on how to do that.

**Comment by ghost** [comment]
Where, or how do i add my shared secret?
