### ISSUE TITLE
large appids don't idle

### ISSUE THREAD

**Issue by NotSnowyy** [frk1/steamhourboostv2#28]
I tried several app ids and only short ones like tf2 csgo etc work.
pls fix? :d

nice project btw. keep the good work up

**Comment by goldsolitude** [comment]
you've given examples of short app id's but what about the long ones? AFAIK there's only 6 digit app id's and i've no problem with idling with multiple. make sure that you own the games on your acc.
![image](https://user-images.githubusercontent.com/28206096/37554327-b034e2ac-2a3b-11e8-940b-88bca619818e.png)

**Comment by NotSnowyy** [comment]
this is what i do: "games": [
      730, 440, 601510
    ]
601510 is Yu-Gi-Oh! Duel Links which is f2p. CS:GO and TF2 both work. 601510 does not.

**Comment by Chino0147** [comment]
You have to play the f2p game once to add it to library.

**Comment by NotSnowyy** [comment]
Alright thank you very much it works now. I was just confused because TF2 for example worked even without starting it once. This issue is fixed then i guess.

**Comment by frk1** [comment]
As @Chino0147 said, you have to play those f2p games once for them to start working.

TF2 works because you bought this game (or received it with some other package).
