### ISSUE TITLE
telebot is flooding me

### ISSUE THREAD

**Issue by xCorteX** [frk1/steamhourboostv2#29]
_node **v9.8.0**
 pm2 **2.10.1**
 npm **5.6.0**
yarn **1.5.1**_

steam_bot, [19.03.18 18:03]
The following accounts are available:
- lxxxxxxxx
- 6xxxxxxxx
- hxxxxxxx
- exxxxxx
- axxxxxxxxxx

steam_bot, [19.03.18 18:03]
Could not find a matching account!

Try /list to get a list of available accounts!

steam_bot, [19.03.18 18:03]
Could not find a matching account!

Try /list to get a list of available accounts!

steam_bot, [19.03.18 18:03]
The following accounts are available:
- lxxxxxxxx
- 6xxxxxxxx
- hxxxxxxx
- exxxxxx
- axxxxxxxxxx

steam_bot, [19.03.18 18:03]
Could not find a matching account!

Try /list to get a list of available accounts!

steam_bot, [19.03.18 18:03]
Could not find a matching account!

Try /list to get a list of available accounts!

steam_bot, [19.03.18 18:03]
The following accounts are available:
- lxxxxxxxx
- 6xxxxxxxx
- hxxxxxxx
- exxxxxx
- axxxxxxxxxx

steam_bot, [19.03.18 18:03]
Could not find a matching account!

Try /list to get a list of available accounts!

steam_bot, [19.03.18 18:03]
Could not find a matching account!

Try /list to get a list of available accounts!

steam_bot, [19.03.18 18:03]
Selected account 6xxxxx.

2FA-Code: MQ32H

steam_bot, [19.03.18 18:03]
Selected account lxxxxxx.

2FA-Code: 6J3X8

**Comment by frk1** [comment]
Restart the bot. The problem is related to the telegram so theres not much I can do.
