### ISSUE TITLE
cant log in with steam auth

### ISSUE THREAD

**Issue by SiqSardines** [frk1/steamhourboostv2#32]
tried entering my steam auth code but it wont work

**Comment by Chino0147** [comment]
because it doesn't support steam auth code.
Only steam guard with mail or use 2-factor shared secret.

**Comment by SiqSardines** [comment]
whats 2-factor shared secret? cuz i wanna use it on my main acc but still wanna be able to trade

**Comment by Chino0147** [comment]
it's inside 
root/data/data/com.valvesoftware.android.steam.community/f/Steamguard-STEAMID64

**Comment by Chino0147** [comment]
^^^
if your phone is an android and rooted
