### ISSUE TITLE
Add account error....

### ISSUE THREAD

**Issue by ghost** [frk1/steamhourboostv2#36]
Ubuntu 16.04 x64

? Password: [hidden]
net.js:423
    this[kTimeout] = setUnrefTimeout(this._onTimeout.bind(this), msecs);
                                                     ^

TypeError: Cannot read property 'bind' of undefined
    at TCPConnection.Socket.setTimeout (net.js:423:54)
    at /root/steamhourboostv2/node_modules/steam-client/lib/cm_client.js:175:21
    at TCPConnection.connect (/root/steamhourboostv2/node_modules/steam-client/lib/tcp_connection.js:97:3)
    at _getServer (/root/steamhourboostv2/node_modules/steam-client/lib/cm_client.js:119:20)
    at CMClient._getServer (/root/steamhourboostv2/node_modules/steam-client/lib/cm_client.js:442:3)
    at CMClient.connect (/root/steamhourboostv2/node_modules/steam-client/lib/cm_client.js:97:7)
    at gotCMList (/root/steamhourboostv2/node_modules/steam-user/components/logon.js:171:17)
    at /root/steamhourboostv2/node_modules/steam-user/components/logon.js:132:6
    at Gunzip.<anonymous> (/root/steamhourboostv2/node_modules/steam-user/components/webapi.js:85:4)
    at Gunzip.emit (events.js:187:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! steamhourboostv2@4.1.2 user: `node lib/user.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the steamhourboostv2@4.1.2 user script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-27T18_48_41_351Z-debug.log
root@xdafis:~/steamhourboostv2#

--logs from file
0 info it worked if it ends with ok
1 verbose cli [ '/root/.n/bin/node', '/root/.n/bin/npm', 'run', 'user' ]
2 info using npm@5.6.0
3 info using node@v10.0.0
4 verbose run-script [ 'preuser', 'user', 'postuser' ]
5 info lifecycle steamhourboostv2@4.1.2~preuser: steamhourboostv2@4.1.2
6 info lifecycle steamhourboostv2@4.1.2~user: steamhourboostv2@4.1.2
7 verbose lifecycle steamhourboostv2@4.1.2~user: unsafe-perm in lifecycle true
8 verbose lifecycle steamhourboostv2@4.1.2~user: PATH: /root/.n/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/steamhourboostv2/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/.n/bin
9 verbose lifecycle steamhourboostv2@4.1.2~user: CWD: /root/steamhourboostv2
10 silly lifecycle steamhourboostv2@4.1.2~user: Args: [ '-c', 'node lib/user.js' ]
11 silly lifecycle steamhourboostv2@4.1.2~user: Returned: code: 1  signal: null
12 info lifecycle steamhourboostv2@4.1.2~user: Failed to exec user script
13 verbose stack Error: steamhourboostv2@4.1.2 user: `node lib/user.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.n/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/root/.n/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:947:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
14 verbose pkgid steamhourboostv2@4.1.2
15 verbose cwd /root/steamhourboostv2
16 verbose Linux 4.4.0-92-generic
17 verbose argv "/root/.n/bin/node" "/root/.n/bin/npm" "run" "user"
18 verbose node v10.0.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error steamhourboostv2@4.1.2 user: `node lib/user.js`
22 error Exit status 1
23 error Failed at the steamhourboostv2@4.1.2 user script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by frk1** [comment]
Should be fixed in 13e6cc043c5b42fe4480308c8d929e38ca2562b5.
