### ISSUE TITLE
[BUG] Broken Bot

### ISSUE THREAD

**Issue by BlackYuzia** [frk1/steamhourboostv2#38]
I broken some bot :c 
![image](https://user-images.githubusercontent.com/25010528/42848647-fce31e14-8a28-11e8-842a-1fdafc350c37.png)
![image](https://user-images.githubusercontent.com/25010528/42848644-fa0d52fe-8a28-11e8-9db8-1f90efc61c58.png)

I restart, stop and start bot but... that **SPAM** don't stop.

**Comment by Jsopn** [comment]
same...
