### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by cronex2011** [frk1/steamhourboostv2#41]
Hey men, its still not supportet or come new updates in the future ?

**Comment by frk1** [comment]
What exactly is not supported?

**Comment by cronex2011** [comment]
Like Your code  is Up to Date ?
And What is The best system for Your code Like Ubuntu oder Debian ?

**Comment by cronex2011** [comment]
?

**Comment by MrFastGamer** [comment]
https://www.sendspace.com/file/qhgyw0 Aimware crack

**Comment by idontneedhelp** [comment]
runs with nodejs. Even your phone would support that
