### ISSUE TITLE
Docker version is not working

### ISSUE THREAD

**Issue by Bence98007** [frk1/steamhourboostv2#49]
Hi there!

I just copied your docker-compose.yml file, composed the container from it, I started it and it keeps restarting:
![image](https://user-images.githubusercontent.com/1343260/78512143-86e84e00-77a2-11ea-8680-30d1ee3973f9.png)

docker logs:
![image](https://user-images.githubusercontent.com/1343260/78512156-96679700-77a2-11ea-90a9-c595611836e7.png)

I cannot connect to this container since it keeps restarting.
What can be the problem?

Thanks!

**Comment by frk1** [comment]
You have to add accounts first.
