### ISSUE TITLE
Stop boost after run game on your pc

### ISSUE THREAD

**Issue by ceregapro1** [frk1/steamhourboostv2#55]
If i run game which now boost on my vps by SHBv2, boost was stopped and not wanna start boost again after close game. yes i can make cron task:
* */1 * * * /usr/local/bin/pm2 restart all
but when i loose some times for that, maybe update script?

**Comment by ceregapro1** [comment]
why close?

**Comment by frk1** [comment]
It will start to boost again after some time.

**Comment by ceregapro1** [comment]
how reduce that time?

**Comment by frk1** [comment]
You can't without changing the code. If you want that, you have to figure it out yourself.
