### ISSUE TITLE
Is this script interacting with the new Tursted mode on CS:GO?

### ISSUE THREAD

**Issue by kblade07** [frk1/steamhourboostv2#56]
Hello.

Is this script interacting with the new tursted mode on cs:go? Will this trigger the low trust factor when cs go is opened on the VPS?
Any ideas?

**Comment by ReactiioN1337** [comment]
> Trusted mode in CS:GO blocks third-party files from interacting with the game and is enabled by default for all CS:GO players.

You could have saved yourself the question by reading the [official FAQ](https://support.steampowered.com/kb_article.php?ref=8835-KLXV-0292).

**Comment by kblade07** [comment]
> > Trusted mode in CS:GO blocks third-party files from interacting with the game and is enabled by default for all CS:GO players.
> 
> You could have saved yourself the question by reading the [official FAQ](https://support.steampowered.com/kb_article.php?ref=8835-KLXV-0292).

Ive done it a long time ago and I don't find anything useful there. I don't know how this scrip works or how it is opening cs:go (opening CS:GO in virtualization mode or outside of steam will trigger this) so thats why I asked the creator of the script.

**Comment by ReactiioN1337** [comment]
This script does **not** attach any game process. Steam provides a Web API which is being called via nodejs.
