### ISSUE TITLE
Basic questions

### ISSUE THREAD

**Issue by Darkroz** [frk1/steamhourboostv2#6]
Hello,
Steamhourboostv2 is installed on my VPS, i managed to add users but how can i remove some user ?
How can i change games to farm ?

Thanks for answers

**Comment by TheRhanderson** [comment]
Use a FTP client to access your vps.

**Comment by Darkroz** [comment]
ok i've found how to do it with FTP client thanks :D 
If someone want to know : 
By default it will boost the games CS 1.6 and CS:GO. If you want to change the games that are being boosted, edit the config/database.json directly!
take the ID number of the game that you want (ex: for CSGO it's 730 look at the link on the steam page of CSGO) and then put it on the account that you want with orther IDs ex

         730,
         10,
          760

**Comment by frk1** [comment]
You have to manually edit your `database.json` in the folder `config`.

If you don't know the syntax, use a tool like http://www.jsoneditoronline.org.
