### ISSUE TITLE
Big problem

### ISSUE THREAD

**Issue by bagietka555** [frk1/steamhourboostv2#8]
Hi got some problem since yesterday this script is not working
I found this article got some problem while trying to put yarn install nth happens only :~/steamhourboostv2# yarn install
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.26s.
When i try to npm run user: npm ERR! missing script: user

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-10T20_40_02_754Z-debug.log
Can't deal with it please help me...

**Comment by bagietka555** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! steamhourboostv2@4.0.1 user: `coffee src/user.coffee`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the steamhourboostv2@4.0.1 user script.
npm ERR! This is probably not a problem with npm. There is likely additional log          ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-10T20_59_24_768Z-debug.log
root@vps245647:~/steamhourboostv2/steamhourboostv2# npm run user

**Comment by frk1** [comment]
Update your version, should be fixed now.

**Comment by bagietka555** [comment]
yeap I just reinstalled my own vps then did as u said everything's ok ty
